name: video_api
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pocketbase: ^0.4.1
  flutter_riverpod: ^2.0.2
  go_router: ^5.1.1
  flutter_widget_from_html_core: any
  fwfh_webview: ^0.6.2
  url_launcher: ^6.1.6
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.12

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
